// tests/wasm.rs — exercise the JS↔Rust boundary of WasmBudgetTree.
//
// Run with:
//   wasm-pack test --node --features wasm
//
// These tests construct the real WasmBudgetTree (embedded budauth.csv)
// and verify the changeset shape and cascade semantics that the Vue
// store relies on. Pure-Rust tests of the same algorithm live in
// src/adjust.rs and src/node.rs; this file exists to catch regressions
// where the algorithm is correct but the wasm-bindgen marshalling drops
// or corrupts data.

#![cfg(all(target_arch = "wasm32", feature = "wasm"))]

// Node is the default test target; no wasm_bindgen_test_configure! needed.
use wasm_bindgen_test::*;
use tnv_budget_tree::wasm::WasmBudgetTree;

// Latest year present in the embedded budauth.csv. The real .env may use a
// later year once the CSV is regenerated by tnv-csv-convert.
const FISCAL_YEAR: &str = "2025";

#[derive(serde::Deserialize, Debug, Clone)]
struct NodeMeta {
    idx: usize,
    id: String,
    #[allow(dead_code)]
    name: String,
    level: u8,
    parent: i64,
    value: f64,
    locked: bool,
}

fn fresh_tree() -> WasmBudgetTree {
    WasmBudgetTree::new(0.0, FISCAL_YEAR, "Discretionary", true)
        .expect("WasmBudgetTree::new failed — is budauth.csv present?")
}

fn snapshot(tree: &WasmBudgetTree) -> Vec<NodeMeta> {
    serde_json::from_str(&tree.all_nodes_json()).expect("all_nodes_json parse")
}

/// Find one leaf with at least one unlocked sibling so adjust() can redistribute.
fn first_adjustable_leaf(nodes: &[NodeMeta]) -> NodeMeta {
    for n in nodes {
        if n.parent < 0 { continue; }
        let parent = &nodes[n.parent as usize];
        let leaf_with_sibling = parent.level == 3
            && parent.idx == n.parent as usize
            && nodes.iter().filter(|c| c.parent == n.parent && c.idx != n.idx).count() > 0
            && n.level == 4
            && n.value > 1000.0;
        if leaf_with_sibling { return n.clone(); }
    }
    panic!("no adjustable leaf with sibling found");
}

/// Find a non-leaf (bureau, level 3) with siblings AND children.
fn first_adjustable_bureau(nodes: &[NodeMeta]) -> NodeMeta {
    for n in nodes {
        if n.level != 3 || n.parent < 0 { continue; }
        let has_sibling = nodes.iter().any(|c| c.parent == n.parent && c.idx != n.idx);
        let has_children = nodes.iter().any(|c| c.parent == n.idx as i64);
        if has_sibling && has_children && n.value > 1000.0 {
            return n.clone();
        }
    }
    panic!("no adjustable bureau found");
}

// ─── Basic boundary ──────────────────────────────────────────────

#[wasm_bindgen_test]
fn tree_has_nodes_and_root() {
    let tree = fresh_tree();
    assert!(tree.len() > 50, "tree should have many nodes, got {}", tree.len());
    let root = tree.get_value("root");
    assert!(root > 0.0 && root.is_finite(), "root value = {root}");
}

#[wasm_bindgen_test]
fn all_nodes_json_round_trips() {
    let tree = fresh_tree();
    let nodes = snapshot(&tree);
    assert_eq!(nodes.len(), tree.len());
    assert_eq!(nodes[0].id, "root");
    assert_eq!(nodes[0].parent, -1);
    // every non-root has a real parent
    for n in &nodes[1..] {
        assert!(n.parent >= 0, "{} should have a parent", n.id);
    }
}

// ─── Leaf cascade ────────────────────────────────────────────────

#[wasm_bindgen_test]
fn leaf_increase_redistributes_siblings_keeps_parent_constant() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let leaf = first_adjustable_leaf(&snap);
    let parent_idx = leaf.parent as usize;
    let parent_before = snap[parent_idx].value;

    let target = leaf.value * 1.10; // +10%
    let cs = tree.adjust(&leaf.id, target);

    assert!(cs.len() >= 2, "expected non-empty changeset, got {:?}", &cs[..]);
    assert!(cs.len() % 2 == 0, "changeset must be packed pairs, len={}", cs.len());
    assert!(!cs[0].is_nan(), "first f64 NaN signals error");

    // The leaf itself moved (may be clamped below target if siblings can't fully absorb)
    let leaf_after = tree.get_value(&leaf.id);
    assert!(leaf_after > leaf.value, "leaf should have grown ({} → {})", leaf.value, leaf_after);
    assert!(leaf_after <= target + 1e-3);

    // Parent value should be unchanged (within precision)
    let parent_after = tree.get_value(&snap[parent_idx].id);
    assert!((parent_after - parent_before).abs() < 1.0,
        "parent moved: {parent_before} → {parent_after}");

    // At least one sibling decreased
    let post = snapshot(&tree);
    let any_sibling_dropped = snap.iter().zip(post.iter()).any(|(b, a)| {
        b.parent == leaf.parent && b.idx != leaf.idx && a.value < b.value - 1.0
    });
    assert!(any_sibling_dropped, "no sibling absorbed the delta");
}

#[wasm_bindgen_test]
fn leaf_decrease_lifts_siblings_keeps_parent_constant() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let leaf = first_adjustable_leaf(&snap);
    let parent_idx = leaf.parent as usize;
    let parent_before = snap[parent_idx].value;

    let target = leaf.value * 0.5;
    let _cs = tree.adjust(&leaf.id, target);

    let leaf_after = tree.get_value(&leaf.id);
    assert!(leaf_after < leaf.value, "leaf should have shrunk");

    let parent_after = tree.get_value(&snap[parent_idx].id);
    assert!((parent_after - parent_before).abs() < 1.0,
        "parent moved on decrease: {parent_before} → {parent_after}");

    let post = snapshot(&tree);
    let any_sibling_grew = snap.iter().zip(post.iter()).any(|(b, a)| {
        b.parent == leaf.parent && b.idx != leaf.idx && a.value > b.value + 1.0
    });
    assert!(any_sibling_grew, "no sibling absorbed the released delta");
}

// ─── Non-leaf cascade ────────────────────────────────────────────

#[wasm_bindgen_test]
fn bureau_change_rescales_children_and_adjusts_sibling_bureaus() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let bureau = first_adjustable_bureau(&snap);

    let children_before: Vec<NodeMeta> = snap.iter()
        .filter(|c| c.parent == bureau.idx as i64).cloned().collect();
    let siblings_before: Vec<NodeMeta> = snap.iter()
        .filter(|c| c.parent == bureau.parent && c.idx != bureau.idx).cloned().collect();
    assert!(!children_before.is_empty(), "bureau has no children");
    assert!(!siblings_before.is_empty(), "bureau has no siblings");

    let parent_before = snap[bureau.parent as usize].value;

    let target = bureau.value * 1.20;
    let _cs = tree.adjust(&bureau.id, target);

    let post = snapshot(&tree);

    // 1. Parent total preserved
    let parent_after = post[bureau.parent as usize].value;
    assert!((parent_after - parent_before).abs() < 1.0,
        "agency total moved: {parent_before} → {parent_after}");

    // 2. Children rescaled (most should have changed, sum equals new bureau value)
    let bureau_after = tree.get_value(&bureau.id);
    let child_sum: f64 = children_before.iter()
        .map(|c| post[c.idx].value).sum();
    assert!((child_sum - bureau_after).abs() < 1.0,
        "children sum {child_sum} != bureau value {bureau_after}");
    let any_child_changed = children_before.iter()
        .any(|c| (post[c.idx].value - c.value).abs() > 1.0);
    assert!(any_child_changed, "children were not rescaled");

    // 3. Sibling bureaus together absorbed the delta
    let sibling_sum_before: f64 = siblings_before.iter().map(|s| s.value).sum();
    let sibling_sum_after: f64 = siblings_before.iter()
        .map(|s| post[s.idx].value).sum();
    let absorbed = sibling_sum_before - sibling_sum_after;
    let leaf_delta = bureau_after - bureau.value;
    assert!((absorbed - leaf_delta).abs() < 1.0,
        "sibling pool moved {absorbed}, expected {leaf_delta}");
}

// ─── Locked behavior ─────────────────────────────────────────────

#[wasm_bindgen_test]
fn locked_sibling_is_not_touched() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let leaf = first_adjustable_leaf(&snap);

    // Find a sibling and lock it.
    let sibling = snap.iter().find(|c| c.parent == leaf.parent && c.idx != leaf.idx)
        .expect("sibling exists").clone();
    let other_siblings: Vec<NodeMeta> = snap.iter()
        .filter(|c| c.parent == leaf.parent && c.idx != leaf.idx && c.idx != sibling.idx)
        .cloned().collect();

    if other_siblings.is_empty() {
        // Algorithm needs at least one unlocked sibling. Pick a different leaf
        // for this scenario by skipping.
        return;
    }

    assert!(tree.lock(&sibling.id), "lock should succeed");
    let sibling_before = tree.get_value(&sibling.id);

    let _cs = tree.adjust(&leaf.id, leaf.value * 1.05);

    let sibling_after = tree.get_value(&sibling.id);
    assert!((sibling_after - sibling_before).abs() < 0.01,
        "locked sibling moved: {sibling_before} → {sibling_after}");
}

#[wasm_bindgen_test]
fn locked_node_cannot_be_adjusted() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let leaf = first_adjustable_leaf(&snap);

    assert!(tree.lock(&leaf.id));
    let before = tree.get_value(&leaf.id);
    let cs = tree.adjust(&leaf.id, before * 1.5);

    // wasm.rs returns [NaN] on AdjustError
    assert_eq!(cs.len(), 1);
    assert!(cs[0].is_nan(), "expected NaN sentinel for locked-node adjustment");

    let after = tree.get_value(&leaf.id);
    assert!((after - before).abs() < 0.01, "locked leaf moved: {before} → {after}");
}

// ─── Reset ───────────────────────────────────────────────────────

#[wasm_bindgen_test]
fn reset_node_restores_default_and_cascades() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let leaf = first_adjustable_leaf(&snap);
    let default = leaf.value;

    let _ = tree.adjust(&leaf.id, default * 0.6);
    let after_change = tree.get_value(&leaf.id);
    assert!(after_change < default);

    let cs = tree.reset_node(&leaf.id);
    assert!(!cs.is_empty() && !cs[0].is_nan());
    let restored = tree.get_value(&leaf.id);
    assert!((restored - default).abs() < 1.0,
        "reset didn't restore default: got {restored}, want {default}");
}

#[wasm_bindgen_test]
fn reset_to_default_clears_everything() {
    let mut tree = fresh_tree();
    let snap = snapshot(&tree);
    let leaf = first_adjustable_leaf(&snap);

    let _ = tree.adjust(&leaf.id, leaf.value * 0.4);
    let cs = tree.reset_to_default();
    assert!(!cs.is_empty());

    let post = snapshot(&tree);
    for (b, a) in snap.iter().zip(post.iter()) {
        assert!((b.value - a.value).abs() < 1.0,
            "{} differs after reset: {} → {}", b.id, b.value, a.value);
        assert!(!a.locked, "reset should unlock {}", a.id);
    }
    // Suppress unused-locked warning
    let _ = leaf.locked;
}
